---
swagger: "2.0"
info:
  description: "API Pour l'application de sécurité routière créé pendant la nuit de\
    \ l'info"
  version: "1.0.0"
  title: "nuitdelinfo2017"
  termsOfService: "Sans objet"
  contact:
    email: "test.mail@example.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "inforoute"
  description: "Toutes les infos sur le traffic routier"
- name: "geste"
  description: "Les gestes de premier secours"
schemes:
- "http"
paths:
  /inforoute:
    post:
      tags:
      - "inforoute"
      summary: "Signaler une inforoute"
      description: ""
      operationId: "addInforoute"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Info a ajouter a la liste des inforoutes"
        required: true
        schema:
          $ref: "#/definitions/Inforoute"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Inforoute"
  /inforoute/{infoId}:
    get:
      tags:
      - "inforoute"
      summary: "Obtenir une inforoute"
      description: "Retourne une inforoute"
      operationId: "getInfoById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID de l info route a renvoyer"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Inforoute"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Inforoute not found"
      x-swagger-router-controller: "Inforoute"
    put:
      tags:
      - "inforoute"
      summary: "Mettre a jour une inforoute existante"
      description: ""
      operationId: "updateInforoute"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Inforoute a mettre a jour"
        required: true
        schema:
          $ref: "#/definitions/Inforoute"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Inforoute not found"
        405:
          description: "Validation exception"
      x-swagger-router-controller: "Inforoute"
    delete:
      tags:
      - "inforoute"
      summary: "Supprimer une inforoute"
      description: ""
      operationId: "deleteInforoute"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "petId"
        in: "path"
        description: "Inforoute a supprimer"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Inforoute not found"
      x-swagger-router-controller: "Inforoute"
  /inforoute/all:
    get:
      tags:
      - "inforoute"
      summary: "Recuperer toutes les inforoutes"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "getAllInforoute"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Inforoute"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "Inforoute"
  /geste:
    get:
      tags:
      - "geste"
      summary: "Retourne la liste des gestes qui sauvent"
      description: "Retourne la liste des gestes qui sauvent"
      operationId: "getGestes"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
      x-swagger-router-controller: "Geste"
    post:
      tags:
      - "geste"
      summary: "Ajouter un geste"
      description: ""
      operationId: "addGeste"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Informations sur le geste"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Order"
        400:
          description: "Invalid Order"
      x-swagger-router-controller: "Geste"
  /geste/{gesteId}:
    delete:
      tags:
      - "geste"
      summary: "Supprimer un geste"
      description: ""
      operationId: "deleteGeste"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "orderId"
        in: "path"
        description: "ID du geste à supprimer"
        required: true
        type: "integer"
        minimum: 1
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Order not found"
      x-swagger-router-controller: "Geste"
definitions:
  Inforoute:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      heureCollecte:
        type: "string"
        format: "date-time"
      infoType:
        type: "string"
        description: "Categorie de l info"
        enum:
        - "travaux"
        - "animaux"
        - "accident"
        - "verglas"
        - "eboulement"
      lattitude:
        type: "number"
        format: "float"
      longitude:
        type: "number"
        format: "float"
    xml:
      name: "inforoute"
  Geste:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      titre:
        type: "string"
      description:
        type: "string"
    xml:
      name: "Category"
